#!/usr/bin/env bash

set -euo pipefail

current_dir="$(dirname "${BASH_SOURCE[0]}")"

try_dir="${TRY_DIR:-$HOME/try}"
try_actions_file="${TRY_ACTIONS_file:-$current_dir/lib/actions.sh}"

# get date in format YYYY-MM-DD
date_prefix=$(date +%Y-%m-%d-)

slugify_cmd="tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g'"

folder=$(
	# shellcheck disable=SC2012
	ls "$try_dir" |
		fzf \
			--track \
			--no-clear \
			--preview "tree $try_dir/{}" \
			--prompt "> $date_prefix" \
			--bind "change:transform-query(echo {q} | $slugify_cmd)+reload(echo $date_prefix{q}; ls \"$try_dir\")"
)

project_dir="$try_dir/$folder"

#shellcheck source=./lib/actions/macos.sh
source "$try_actions_file"

selected_actions=$(
	printf '%s\n' "${actions[@]}" |
		fzf --multi --accept-nth 1 --with-nth "{2..}"
)

mkdir -p "$project_dir"

for action in $selected_actions; do
	eval "$action" "$project_dir"
done
